### ISSUE TITLE
bug: no proxy list causes a crash

### ISSUE THREAD

**Issue by taciturnaxolotl** [kcoderhtml/spam-patriot#3]
@Techpro709 noticed in #2 that the program would crash if there wasn't a socks5 proxy file.

**Comment by taciturnaxolotl** [comment]
@Kokonico opening this now but don't feel too rushed on fixing it

**Comment by pxldevv** [comment]
@kcoderhtml, don't feel like fixing it rn, maybe in the distant future

Closed issue 20 minutes after opening.

**Comment by taciturnaxolotl** [comment]
i fixed it with #4
