### ISSUE TITLE
ObjLog usage

### ISSUE THREAD

**Issue by Kokonico** [kcoderhtml/spam-patriot#9]
A python package known as [ObjLog](https://pypi.org/project/ObjLog/) is an object oriented logger for python, it could be used to track many more statistics about the current status of the script, and provide verbose error reports when things go wrong.

it's designed for 1.12.x, and seems to work fine on older versions.

(also, this project works fine on older versions too)

**Comment by taciturnaxolotl** [comment]
This sounds great!

**Comment by Kokonico** [comment]
Heads up:

ObjLog 2.0 is under construction, so we might want to put this off a bit.

**Comment by taciturnaxolotl** [comment]
works for me!

**Comment by Kokonico** [comment]
update:

2.0 is out, we should reprioritize this

**Comment by taciturnaxolotl** [comment]
if you want to inplement it go ahead! i don't have a ton of time to work on it right now but i'll approve any prs!

**Comment by Kokonico** [comment]
got it! I'll begin work on it now!
